### ISSUE TITLE
Getting error while training data

### ISSUE THREAD

**Issue by dheerajnuka** [rikdz/GraphWriter#26]
Hi Team,

I am getting error while executing train.py file 

error:

Traceback (most recent call last):
  File "./train.py", line 128, in <module>
    main(args)
  File "./train.py", line 113, in main
    train(m,o,ds,args)
  File "./train.py", line 28, in train
    for count,b in enumerate(train_iter):
  File "/opt/tljh/user/lib/python3.7/site-packages/torchtext/data/iterator.py", line 157, in __iter__
    yield Batch(minibatch, self.dataset, self.device)
  File "/opt/tljh/user/lib/python3.7/site-packages/torchtext/data/batch.py", line 27, in __init__
    self.input_fields = [k for k, v in dataset.fields.items() if
  File "/opt/tljh/user/lib/python3.7/site-packages/torchtext/data/batch.py", line 28, in <listcomp>
    v is not None and not v.is_target]
AttributeError: 'RawField' object has no attribute 'is_target'

Please let me know if there is any solution for this.

Thanks,
Dheeraj Nuka

**Comment by rikdz** [comment]
Hi Dheeraj, this code is built with an older torchtext, probably around v0.4 or earlier. Please modify as needed!
