### ISSUE TITLE
An Error while executing eval.py

### ISSUE THREAD

**Issue by FlsrageZhang** [rikdz/GraphWriter#27]
Hi Team,
i am getting error while executing eval.py
error:
(fls_n) D:\GraphWriter-master>python eval.py 0.vloss-3.936190.lr-0.1.inputs.beam_predictions.cmdline data/preprocessed.test.tsv
Traceback (most recent call last):
  File "eval.py", line 93, in <module>
    x.evaluate(live=True, cand=cands, ref=refs)
  File "eval.py", line 66, in evaluate
    final_scores = self.score(ref, hypo)
  File "eval.py", line 33, in score
    score, scores = scorer.compute_score(ref, hypo)
  File "D:\GraphWriter-master\pycocoevalcap\meteor\meteor.py", line 40, in compute_score
    self.meteor_p.stdin.write(score_line + '\n')
OSError: [Errno 22] Invalid argument

Please let me know if there is any solution for this error.

Thanks,
Flsrage

**Comment by rikdz** [comment]
Are you running on Windows/DOS OS? This error might be a problem with the meteor eval script and windows. I am unsure how to debug... maybe change it to self.meteor_p.write(score_line + '\n')`
